book/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'book'
urlpatterns = [
    # 书籍详情
    path('detail/<int:book_id>/', views.detail, name='detail'),
    # 书籍分类
    path('kind/<int:kind_id>/', views.kind, name='kind'),
    #搜索书籍结果
    path('search/', views.search, name='search'),
    # 加入购物车指定本书（缺省为1）
    path('buy/', views.buy, name='buy'),
    # 删除用户购物车中商品的信息
    path('cancel/', views.cancel, name='cancel'),
    # 购物车书数目设置为
    path('set_number/', views.set_number, name='set_number'),
    # 购物车书选中状态反转
    path('select/', views.select, name='select'),
    # 获取用户购物车中商品的数量（无论选不选中的商品种类数）
    path('count/', views.count, name='count'),
    # 购物车已选中数量
    path('select_count/', views.select_count, name='select_count'),
    #path('update/', views.cart_update, name="update"),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('user/', include('user.urls')),
    path('book/', include('book.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

order/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'order'
urlpatterns = [
    # 自己的全部订单
    path('all/', views.all, name='all'),
    # 订单详情
    path('detail/<int:order_id>/', views.detail, name='detail'),
    # 将购物车中的全部货物提交订单
    path('new/', views.new, name='new'),
    # 立即购买 直接创建订单
    path('buynow/', views.buynow, name='buynow'),
    # 订单确认收货
    path('receive/', views.receive, name='receive'),
    # 订单支付宝支付
    path('alipay_pay/', views.alipay_pay, name='alipay_pay'),
    # （已改为一般函数）
    # path('alipay_query/', views.alipay_query, name='alipay_query'),
]

user/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'user'
urlpatterns = [
    # ex: /user/
    path('login/', views.login, name='login'),
    path('detail/', views.detail, name='detail'),
    path('register/', views.register, name="register"),
    path('result/', views.result, name="result"),
    path('logout/', views.logout, name="logout"),
    path('cart/', views.cart, name="cart"),
    # path('order/', views.order, name="order"), TODO 订单确认页面
    path('verifycode/', views.verifycode, name="verifycode"),
    path('verifyemail/', views.verifyemail, name="verifyemail"),
    path('login_check/', views.login_check, name="login_check"),
    # path('register_update/', views.register_update, name="register_update"), TODO 更新个人信息

    #关于统计信息的超级用户的url
    path('super/', views.super_host, name="super_host"),
    path('super/book/<int:pageid>/', views.super_book, name="super_book"),
    path('super/book/bookadd/', views.super_bookadd, name="super_bookadd"),
    path('super/book/create/', views.super_bookCreate, name="super_bookCreate"),
    path('super/book/delete/<int:bookid>/', views.super_bookDelete, name="super_bookDelete"),
    path('super/book/change/<int:bookid>/', views.super_bookChange, name="super_bookChange"),
    path('super/book/update/<int:bookid>/', views.super_bookUpdate, name="super_bookUpdate"),
    path('super/statistic/', views.statistic, name="statistic"),
    path('super/order/<int:pageid>/', views.super_order, name="super_oder"),
    path('super/order/status/<int:orderid>/', views.super_orderSta),
]

templates/base.html
{# 首页 登录 注册 的父模板 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页顶部标题 #}
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>

<style>
.con {
/* 要创建一个 flex 容器，只需要将一个 display: flex 属性添加到一个元素上。
默认情况下，所有的直接子元素都被认为是 flex 项，并从左到右依次排列在一行中。
如果 flex 项的宽度总和大于容器，那么 flex 项将按比例缩小，直到它们适应 flex 容器宽度 */
display: flex;
/* flex-direction 决定主轴的方向 row(默认)|row-reverse|column|column-reverse*/
/* flex-direction: row; */
/* flex-wrap决定当排列不下时是否换行以及换行的方式,nowrap(默认)|wrap|wrap-reverse */
/* flex-wrap:wrap; */
/* flex-flow是lex-direction和flex-wrap的简写形式，如：row wrap|column wrap-reverse等。默认值为row nowrap，即横向排列 不换行 */
flex-flow:row wrap;
/* !当主轴沿水平方向时!justify-content,决定item在主轴上的对齐方式，可能的值有flex-start（默认），flex-end，center，space-between，space-around */
justify-content:center;
/* !主轴水平时!决定了item在交叉轴上的对齐方式，可能的值有flex-start|flex-end|center|baseline|stretch */
align-items:center;
}

.con>div {
width: 160px;
height: 180px;
background: #ffffff;
border: 1px solid white;
margin-left: 40px;
text-align: center;
line-height:100px;
}

.con_index {
display: flex;
flex-flow:row wrap;
justify-content:center;
align-items:center;
}

.con_index>div {
width: 160px;
height: 224px;
background: #ffffff;
border: 1px solid white;
margin-left: 50px;
    margin-top: 35px;
text-align: center;
line-height:100px;
}


.book_kind_con{
	width:1198px;
	height:798px;
	border:1px solid #ededed;
	margin:0 auto 20px;
}

.user_info_list1{
	background-color:#f9f9f9;
	margin:10px 0 15px;
	padding:10px 0;
	height:120px;
}

.user_info_list1 li{
	line-height:30px;
	text-indent:30px;
	font-size:14px;
}

.user_info_list1 li span{
	width:100px;
	float:left;
	text-align:right;
}


</style>

    {% block cart_count %}
        <script>
        $(function () {
            window.update_select_count = function() {
                $.get('/book/select_count/', function (data) {
                    // {'res':商品的总数}
                    $('#show_count').html(data.res)
                })
            }
            update_select_count()
        })
        </script>
    {% endblock cart_count %}
    {% block topfiles %}
    {# 网页顶部引入文件 #}
    {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到珞珈网上书店!</div>
            <div class="fr">
                {% if request.session.islogin %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ request.session.user.user_name }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:detail' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'user:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'order:all' %}">我的订单</a>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                {% endif %}
            </div>
        </div>      
    </div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'index' %}" class="logo fl"> <img src="{% static 'images/logo.png' %}" style="width: 88px; height: 88px;"> </a>
        <div class="search_con fl">
            <form method='post' action='{% url 'book:search' %}' target="_blank">{% csrf_token %}
                <input type="text" required="required" class="input_text fl" name="keyword" placeholder="请输入想要查找的图书">
                <input type="submit"  class="input_btn fr" value="查询">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'user:cart' %}" class="cart_name fl">我的购物车</a>
            <div class="book_count fl" id="show_count">0</div>
        </div>
    </div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="mailto: yusitong1999@foxmail.com">联系我们</a>
        </div>
        <p>CopyRight © 2020 珞珈网上书店 All Rights Reserved</p>
        <p>E-Mail: yusitong1999@foxmail.com</p>
    </div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li><a href="#model01" class="python">经济</a></li>
            <li><a href="#model02" class="javascript">科幻</a></li>
            <li><a href="#model03" class="algorithms">科技</a></li>
            <li><a href="#model04" class="machinelearning">生活</a></li>
            <li><a href="#model05" class="operatingsystem">文学</a></li>
            <li><a href="#model06" class="operatingsystem">推荐</a></li>
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="{% static 'images/slide0.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide1.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide2.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide3.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="{% static 'images/slide1.jpg' %}" style="width: 240px; height: 135px;"></a>
            <a href="#"><img src="{% static 'images/slide2.jpg' %}" style="width: 240px; height: 135px;"></a>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model01">经济</h3>
            <div class="subtitle fl">
                <span>|</span>

            </div>
            <a href="book/kind/1" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/43/"><img src="static/bookimages/43.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/47/"><img src="static/bookimages/47.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/52/"><img src="static/bookimages/52.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/55/"><img src="static/bookimages/55.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/60/"><img src="static/bookimages/60.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>
    </div>






    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model02">科幻</h3>
            <div class="subtitle fl">
                <span>|</span>
            </div>
            <a href="book/kind/2" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/81/"><img src="static/bookimages/81.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/82/"><img src="static/bookimages/82.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/86/"><img src="static/bookimages/86.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/90/"><img src="static/bookimages/90.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/94/"><img src="static/bookimages/94.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model03">科技</h3>
            <div class="subtitle fl">
                <span>|</span>
            </div>
            <a href="book/kind/3" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/61/"><img src="static/bookimages/61.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/64/"><img src="static/bookimages/64.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/65/"><img src="static/bookimages/65.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/70/"><img src="static/bookimages/70.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/75/"><img src="static/bookimages/75.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>

    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model04">生活</h3>
            <div class="subtitle fl">
                <span>|</span>
            </div>
            <a href="book/kind/4" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/23/"><img src="static/bookimages/23.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/27/"><img src="static/bookimages/27.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/28/"><img src="static/bookimages/28.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/34/"><img src="static/bookimages/34.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/38/"><img src="static/bookimages/38.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>

    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model05">文学</h3>
            <div class="subtitle fl">
                <span>|</span>
            </div>
            <a href="book/kind/5" class="book_more fr">查看更多 ></a>
        </div>

        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/1/"><img src="static/bookimages/1.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/2/"><img src="static/bookimages/2.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/3/"><img src="static/bookimages/3.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/8/"><img src="static/bookimages/8.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/13/"><img src="static/bookimages/13.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>

    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model06">推荐</h3>
            <div class="subtitle fl">
                <span>|</span>
            </div>
        </div>


        <div class="book_con clearfix">
            <div class='con_index'>
                <div>
                    <a href="book/detail/17/"><img src="static/bookimages/17.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/33/"><img src="static/bookimages/33.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/54/"><img src="static/bookimages/54.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/80/"><img src="static/bookimages/80.jpg" height="224" width="160"></a>
                </div>
                <div>
                    <a href="book/detail/92/"><img src="static/bookimages/92.jpg" height="224" width="160"></a>
                </div>

            </div>
        </div>

    </div>

{% endblock body %}