book/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'book'
urlpatterns = [
    # 书籍详情
    path('detail/<int:book_id>/', views.detail, name='detail'),
    # 书籍分类
    path('kind/<int:kind_id>/', views.kind, name='kind'),
    #搜索书籍结果
    path('search/', views.search, name='search'),
    # 加入购物车指定本书（缺省为1）
    path('buy/', views.buy, name='buy'),
    # 删除用户购物车中商品的信息
    path('cancel/', views.cancel, name='cancel'),
    # 购物车书数目设置为
    path('set_number/', views.set_number, name='set_number'),
    # 购物车书选中状态反转
    path('select/', views.select, name='select'),
    # 获取用户购物车中商品的数量（无论选不选中的商品种类数）
    path('count/', views.count, name='count'),
    # 购物车已选中数量
    path('select_count/', views.select_count, name='select_count'),
    #path('update/', views.cart_update, name="update"),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('user/', include('user.urls')),
    path('book/', include('book.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

order/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'order'
urlpatterns = [
    # 自己的全部订单
    path('all/', views.all, name='all'),
    # 订单详情
    path('detail/<int:order_id>/', views.detail, name='detail'),
    # 将购物车中的全部货物提交订单
    path('new/', views.new, name='new'),
    # 立即购买 直接创建订单
    path('buynow/', views.buynow, name='buynow'),
    # 订单确认收货
    path('receive/', views.receive, name='receive'),
    # 订单支付宝支付
    path('alipay_pay/', views.alipay_pay, name='alipay_pay'),
    # （已改为一般函数）
    # path('alipay_query/', views.alipay_query, name='alipay_query'),
]

user/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'user'
urlpatterns = [
    # ex: /user/
    path('login/', views.login, name='login'),
    path('detail/', views.detail, name='detail'),
    path('register/', views.register, name="register"),
    path('result/', views.result, name="result"),
    path('logout/', views.logout, name="logout"),
    path('cart/', views.cart, name="cart"),
    # path('order/', views.order, name="order"), TODO 订单确认页面
    path('verifycode/', views.verifycode, name="verifycode"),
    path('verifyemail/', views.verifyemail, name="verifyemail"),
    path('login_check/', views.login_check, name="login_check"),
    # path('register_update/', views.register_update, name="register_update"), TODO 更新个人信息

    #关于统计信息的超级用户的url
    path('super/', views.super_host, name="super_host"),
    path('super/book/<int:pageid>/', views.super_book, name="super_book"),
    path('super/book/bookadd/', views.super_bookadd, name="super_bookadd"),
    path('super/book/create/', views.super_bookCreate, name="super_bookCreate"),
    path('super/book/delete/<int:bookid>/', views.super_bookDelete, name="super_bookDelete"),
    path('super/book/change/<int:bookid>/', views.super_bookChange, name="super_bookChange"),
    path('super/book/update/<int:bookid>/', views.super_bookUpdate, name="super_bookUpdate"),
    path('super/statistic/', views.statistic, name="statistic"),
    path('super/order/<int:pageid>/', views.super_order, name="super_oder"),
    path('super/order/status/<int:orderid>/', views.super_orderSta),
]

order/models.py
from django.db import models

# Create your models here.


class Order(models.Model):
    def __str__(self):
        return str(self.order_id)

    order_id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    sum_price = models.FloatField()
    # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
    status = models.IntegerField()
    time_submit = models.DateTimeField()
    time_pay = models.DateTimeField(null=True)
    time_finish = models.DateTimeField(null=True)


class OrderContent(models.Model):
    def __str__(self):
        return str(self.book_id)

    order_id = models.IntegerField()
    book_id = models.IntegerField()
    number = models.IntegerField()
    price = models.FloatField()

order/views.py
import io

from django.forms import model_to_dict
from django.http import JsonResponse, Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
from book.models import Book
from user.models import Cart
from order.models import Order, OrderContent
from django.core import serializers
from bookstore import settings

import datetime

from alipay import AliPay  # https://blog.csdn.net/appleyuchi/article/details/104613313
import qrcode, time
import urllib

from bookstore.views import login_needful, login_needful_json_res_0_errmsg


@login_needful
def all(request) -> HttpResponse:
    """用户的所有信息"""
    user_id = request.session['user']['user_id']

    # 更新待支付订单状态
    for order in Order.objects.filter(user_id=user_id, status=1):
        # ？频繁连续查询失败概率明显提高？同一顾客不太可能有过多待支付订单
        order_status_update(order)
    def Add_Content(order):
        dic = {0: '已取消', 1: '待付款', 2: '待发货', 3: '已发货', 4: '已完成'}
        order = model_to_dict(order)
        order['status'] = dic[order['status']]
        order_content_list = OrderContent.objects.filter(order_id=order['order_id'])
        order_content = []
        for o_c in order_content_list:
            o_c = model_to_dict(o_c)
            o_c['books'] = Book.objects.get(book_id=o_c['book_id'])
            o_c['price'] = o_c['price'] * o_c['number']
            order_content.append(o_c)
        order['order_content'] = order_content
        return order
    cancel_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=0)]
    unpaid_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=1)]
    unsent_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=2)]
    unreceived_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=3)]
    finished_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=4)]
    content = {
        'cancel_list': cancel_list,
        'unpaid_list': unpaid_list,
        'unsent_list': unsent_list,
        'unreceived_list': unreceived_list,
        'finished_list': finished_list,
    }
    # 因为没有对应前端，先返回成json
    return render(request, 'order/all.html', content)


@login_needful
def detail(request, order_id: int):
    """订单详情 TODO 只能查看自己的订单"""
    content = {}
    # 订单本身的信息
    try:
        order = Order.objects.get(order_id=order_id)
    except Cart.DoesNotExist:
        return Http404
    except Cart.MultipleObjectsReturned:
        raise Exception('同一订单号出现多次')

    # 更新待支付订单状态
    order_status_update(order)

    # object 转 dict
    content['order'] = model_to_dict(order)
    # 计算总付款数=总价+运费
    content['order']['all_price'] = content['order']['sum_price'] + 10
    content['order']['status_str'] = settings.STATUS_NUM_TO_STR[order.status]

    # 订单中书籍的信息
    content['order_content'] = []
    order_content = OrderContent.objects.filter(order_id=order_id)
    content['count'] = len(order_content)
    for book in order_content:
        element = {
            'id': book.order_id,
            'book_id': book.book_id,
            'number': book.number,
            'price': book.price * book.number,  # 小计：可能不只一本同种书的总价
        }
        try:
            book = Book.objects.get(book_id=book.book_id)
        except Cart.DoesNotExist:
            raise Exception('书编号%d不存在' % book.book_id)
        except Cart.MultipleObjectsReturned:
            raise Exception('书编号%d出现多次' % book.book_id)
        element.update({
            'book_name': book.book_name,
            'book_picture': book.book_picture,
            'book_price': book.price,
            'author': book.author,
            'press': book.press,
            'kind_name': book.kind_name,
        })
        content['order_content'].append(element)
        #收货地址
        content['address'] = request.session['user']['address']
        content['user_name'] = request.session['user']['user_name']
        content['phone_number'] = request.session['user']['phone_number']
    return render(request, 'order/detail.html', content)


@login_needful
def new(request):
    """创建订单，以购物车中选中的商品"""
    order = Order(
        # order_id =
        user_id=request.session['user']['user_id'],
        sum_price=0,
        # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
        status=1,
        time_submit=datetime.datetime.now(),
        # time_pay=None,
        # time_finish=None,
    )
    order.save()

    sum_price = 0.0
    for book in Cart.objects.filter(
            user_id=request.session['user']['user_id'],
            select=True,
    ).all():
        OrderContent.objects.create(
            order_id=order.order_id,
            book_id=book.book_id,
            number=book.number,
            price=book.price
        )
        sum_price += book.number * book.price
    Order.objects.filter(order_id=order.order_id).update(sum_price=sum_price)
    Cart.objects.filter(
        user_id=request.session['user']['user_id'],
        select=True,
    ).delete()
    # 重定向展示实际的网址
    return redirect("/order/detail/%d" % order.order_id)


@login_needful_json_res_0_errmsg
def buynow(request) -> JsonResponse:
    """立即购买，以给定数量当前商品创建订单"""
    try:
        book_id = int(request.GET.get('book_id'))
        number = int(request.GET.get('number', 1))
    except ValueError:
        # 商品数目不合法
        return JsonResponse({'res': 0, 'errmsg': '商品数量必须为数字'})
    book = Book.objects.get(book_id=book_id)

    order = Order(
        user_id=request.session['user']['user_id'],
        sum_price=number*book.price,
        # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
        status=1,
        time_submit=datetime.datetime.now()
    )
    order.save()

    OrderContent.objects.create(
        order_id=order.order_id,
        book_id=book_id,
        number=number,
        price=book.price
    )
    return JsonResponse({'res':1, 'order_id':order.order_id})


@login_needful_json_res_0_errmsg
def receive(request) -> JsonResponse:
    """订单收货 TODO 仅限自己的订单"""
    try:
        order_id = int(request.GET.get('order_id'))
    except ValueError:
        return JsonResponse({'res': 0, 'errmsg': '订单号错误'})
    try:
        order = Order.objects.get(user_id=request.session['user']['user_id'], order_id=order_id)
    except Order.DoesNotExist:
        # 订单不存在
        return JsonResponse({'res': 0, 'errmsg': '订单不存在'})
    except Order.MultipleObjectsReturned:
        raise Exception('订单表错误')
    if order.status == 3:
        # 将可收货的订单收货
        order.status = 4
        order.save()
        return JsonResponse({'res': 1})
    else:
        return JsonResponse({'res': 0, 'errmsg': '订单不可收货'})


alipayClient = AliPay(
    appid=settings.APP_ID,
    app_notify_url=None,
    app_private_key_string=settings.APP_PRIVATE_KEY,
    alipay_public_key_string=settings.ALIPAY_PUBLIC_KEY,
    sign_type='RSA2',
    debug=settings.DEBUG,
)


def build_trade_no(order_id: int, date_time: datetime):
    """以订单号和日期时间构造支付宝订单号"""
    return (str(order_id) + '__%s' % date_time).split('.')[0].replace(' ', '_').replace('-', '_').replace(':', '_')


def alipay_pay(request):
    """获取支付宝支付二维码 TODO 限用户个人"""
    global alipayClient

    order_id = request.GET.get('order_id')
    if order_id is None:
        print('无order_id')
        return
    try:
        order_id = int(order_id)
    except ValueError:
        print('order_id非整数')
        return
    try:
        order = Order.objects.get(order_id=order_id)
    except Order.DoesNotExist:
        # 订单不存在
        print('order_id 订单不存在')
        return
    except Order.MultipleObjectsReturned:
        raise Exception('订单表错误')

    # 支付宝订单号
    out_trade_no = build_trade_no(order_id, order.time_submit)
    print(out_trade_no)
    # 书籍总价加运费
    total_amount = order.sum_price + 10.00
    subject = '珞珈在线书店订单 %s' % order.time_submit
    timeout_express = '30m'
    try:
        dict = alipayClient.api_alipay_trade_precreate(out_trade_no=out_trade_no, total_amount=total_amount,
                                                       subject=subject, timeout_express=timeout_express)
    except urllib.error.URLError:
        raise Exception('网络已断开')

    # https://www.cnblogs.com/linjiqin/p/4140455.html
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=2,  # 图片尽可能小，但足以识别（结果一般为86*86像素）
        border=1
    )
    qr.add_data(dict['qr_code'])  # 从URL获取二维码所含信息
    img = qr.make_image()  # 生成二维码图片
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为png
    img.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


def alipay_query(out_trade_no: str):
    """查询支付宝未付款订单最新状态"""
    global alipayClient
    try:
        result = alipayClient.api_alipay_trade_query(out_trade_no=out_trade_no)
    except:
        return {'res': 0}

    try:
        order_id = int(out_trade_no.split('_')[0])
    except ValueError:
        raise Exception('order_id非整数 %s' % out_trade_no)

    if result.get('code', '') == '40004':
        if result.get('sub_code', '') == 'ACQ.TRADE_NOT_EXIST':
            # 用户未扫码，支付宝订单未创建
            return {'res': 1, 'status': 1}
        else:
            # 调用失败
            return {'res': 0}
    elif result.get('code', '') == '10000':
        try:
            order = Order.objects.get(order_id=order_id)
        except Order.DoesNotExist:
            # 订单不存在
            raise Exception('order_id 订单不存在 %d' % order_id)
        except Order.MultipleObjectsReturned:
            raise Exception('订单表错误 %d' % order_id)

        # 待支付状态的订单才会被查询，若未支付无需更新
        if result.get("trade_status", "") == "WAIT_BUYER_PAY":
            # 用户扫码，未支付
            return {'res': 1, 'status': 1}
        elif result.get("trade_status", "") == "TRADE_SUCCESS":
            # 用户已支付
            order.status = 2
            order.time_pay = datetime.datetime.now()
            order.save()
            return {'res': 1, 'status': 2}

templates/order/all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
    <style>
    div.show{display:block;}
    div.hide{display:none;}
    </style>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:detail' %}">· 个人信息</a></li>
                <li><a href="{% url 'order:all' %}" class="active">· 全部订单</a></li>
            </ul>
        </div>

        <div class="right_content clearfix">
                {% csrf_token %}
                <h3 class="common_title2">全部订单</h3>

                <div class="r_wrap fr clearfix">
                    <ul class="detail_tab clearfix">
                        <li class="active">已取消</li>
                        <li>待付款</li>
                        <li>待发货</li>
                        <li>已发货</li>
                        <li>已完成</li>
                    </ul>
                </div>

                <div class="show">
                {% for order in cancel_list %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.time_submit }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">{{ order.status }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {# 遍历出来的order_books是一个OrderBooks对象 #}
                                {% for order_books in order.order_content %}
                                <ul class="order_book_list clearfix">
                                    <li class="col01"><img src="{% static order_books.books.book_picture %}"></li>
                                    <li class="col02">{{ order_books.books.book_name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
                                    <li class="col03">{{ order_books.number }}</li>
                                    <li class="col04">{{ order_books.price }}元</li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.sum_price }}元</td>
                            <td width="15%">{{ order.status }}</td>
                            <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                        </tr>
                    </tbody>
                </table>
                {% endfor %}
                </div>


                <div class="hide">
                {% for order in unpaid_list %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.time_submit }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">{{ order.status }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {# 遍历出来的order_books是一个OrderBooks对象 #}
                                {% for order_books in order.order_content %}
                                <ul class="order_book_list clearfix">
                                    <li class="col01"><img src="{% static order_books.books.book_picture %}"></li>
                                    <li class="col02">{{ order_books.books.book_name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
                                    <li class="col03">{{ order_books.number }}</li>
                                    <li class="col04">{{ order_books.price }}元</li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%">{{ order.sum_price }}元</td>
                            <td width="15%">{{ order.status }}</td>
                            <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                        </tr>
                    </tbody>
                </table>
                {% endfor %}
                </div>


                <div class="hide">
                    {% for order in unsent_list %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.time_submit }}</li>
                        <li class="col02">订单号：{{ order.order_id }}</li>
                        <li class="col02 stress">{{ order.status }}</li>
                    </ul>
    
                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {# 遍历出来的order_books是一个OrderBooks对象 #}
                                    {% for order_books in order.order_content %}
                                    <ul class="order_book_list clearfix">
                                        <li class="col01"><img src="{% static order_books.books.book_picture %}"></li>
                                        <li class="col02">{{ order_books.books.book_name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
                                        <li class="col03">{{ order_books.number }}</li>
                                        <li class="col04">{{ order_books.price }}元</li>
                                    </ul>
                                    {% endfor %}
                                </td>
                                <td width="15%">{{ order.sum_price }}元</td>
                                <td width="15%">{{ order.status }}</td>
                                <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                            </tr>
                        </tbody>
                    </table>
                    {% endfor %}
                </div>


                <div class="hide">
                    {% for order in unreceived_list %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.time_submit }}</li>
                        <li class="col02">订单号：{{ order.order_id }}</li>
                        <li class="col02 stress">{{ order.status }}</li>
                    </ul>
    
                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {# 遍历出来的order_books是一个OrderBooks对象 #}
                                    {% for order_books in order.order_content %}
                                    <ul class="order_book_list clearfix">
                                        <li class="col01"><img src="{% static order_books.books.book_picture %}"></li>
                                        <li class="col02">{{ order_books.books.book_name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
                                        <li class="col03">{{ order_books.number }}</li>
                                        <li class="col04">{{ order_books.price }}元</li>
                                    </ul>
                                    {% endfor %}
                                </td>
                                <td width="15%">{{ order.sum_price }}元</td>
                                <td width="15%">{{ order.status }}</td>
                                <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                            </tr>
                        </tbody>
                    </table>
                    {% endfor %}
                </div>


                <div class="hide">
                    {% for order in finished_list %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.time_submit }}</li>
                        <li class="col02">订单号：{{ order.order_id }}</li>
                        <li class="col02 stress">{{ order.status }}</li>
                    </ul>
    
                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {# 遍历出来的order_books是一个OrderBooks对象 #}
                                    {% for order_books in order.order_content %}
                                    <ul class="order_book_list clearfix">
                                        <li class="col01"><img src="{% static order_books.books.book_picture %}"></li>
                                        <li class="col02">{{ order_books.books.book_name }}<em>{{ order_books.books.price }}元/册</em></li>
                                        <li class="col03">{{ order_books.number }}</li>
                                        <li class="col04">{{ order_books.price }}元</li>
                                    </ul>
                                    {% endfor %}
                                </td>
                                <td width="15%">{{ order.sum_price }}元</td>
                                <td width="15%">{{ order.status }}</td>
                                <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                            </tr>
                        </tbody>
                    </table>
                    {% endfor %}
                </div>
        </div>
    </div>

    <script>
$(document).ready(function(){
 $("li").each(function(index){
 //index是li数组的的索引值
 $(this).click(function(){
 var liNode = $(this);
 var id = $(this).attr('id');
  //将原来显示的div隐藏掉
  $("div.show").removeClass("show").addClass("hide");
  //将原来的li的active去掉
  $("li.active").removeClass("active");
  $("div.hide").eq(index-2).removeClass("hide").addClass("show");
  liNode.addClass("active");
 });
 });
 });
    </script>
                <!--
                <div class="pagenation">
                    {% if order_li.has_previous %}
                        <a href="{% url 'user:order' page=order_li.previous_page_number %}">上一页</a>
                    {% endif %}
                    {% for page in pages %}
                        {% if page == order_li.number %}
                            <a href="{% url 'user:order' page=page %}" class="active">{{ page }}</a>
                        {% else %}
                            <a href="{% url 'user:order' page=page %}">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if order_li.has_next %}
                        <a href="{% url 'user:order' page=order_li.next_page_number %}">下一页</a>
                    {% endif %}
                </div>
                -->
{% endblock body %}

templates/order/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}订单详情{% endblock title %}
{% block topfiles %}
<script>
    $(function(){
        $('#order_btn').click(function(){
            var params = {
                "order_id": {{ order.order_id }},
            }
            {% if order.status == 3 %}
            $.get('/order/receive/', params, function (data) {
                if (data.res === 0){
                    // 收货失败
                    alert('收货失败：' + data.errmsg)
                }
            })
            {% endif %}
            window.location.href='/order/detail/' + String({{ order.order_id }})
        })
    })
</script>
{% endblock topfiles %}
{% block body %}

    <h1 class="common_title">{{ order.status_str }}</h1>

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            <dd><input type="radio" name="" checked="">{{address}} （{{user_name}} 收） {{phone_number}}</dd>
        </dl>
    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
{#            <input type="radio" name="pay_style" checked>#}
{#            <label class="cash">货到付款</label>#}
{#            <input type="radio" name="pay_style">#}
            <label class="zhifubao">
                支付宝扫码支付
            </label>
            {% if order.status == 1 %}
                <img style="z-index:1" src="/order/alipay_pay/?order_id={{ order.order_id }}" onclick="this.src='/order/alipay_pay/?order_id={{ order.order_id }}&rnd='+Math.random()" alt="二维码"/>
            {% endif %}
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="book_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for book in order_content %}
        <ul class="book_list_td clearfix">
            <li class="col01">&nbsp;</li>
            <li class="col02"><img src="{% static book.book_picture %}"></li>
            <li class="col03">{{ book.book_name }}</li>
            <li class="col04">册</li>
            <li class="col05">{{ book.book_price }}</li>
            <li class="col06">{{ book.number }}</li>
            <li class="col07">{{ book.price }}元</li>
        </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_book_count">共<em>{{count}}</em>件商品，总金额<b>{{ order.sum_price }}元</b></div>
            <div class="transit">运费：<b>10元</b></div>
            <div class="total_pay">实付款：<b>{{ order.all_price }}</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn" class="order_btn">
        {% if order.status == 3 %} {# 已发货（待收货） #}
            确认收货
        {% elif order.status %}
            刷新订单支付状态
        {% endif %}
        </a>
    </div>
{% endblock body %}
{% block bottom %}
    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>
        <div class="mask"></div>
    </div>
{% endblock bottom %}