book/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'book'
urlpatterns = [
    # 书籍详情
    path('detail/<int:book_id>/', views.detail, name='detail'),
    # 书籍分类
    path('kind/<int:kind_id>/', views.kind, name='kind'),
    #搜索书籍结果
    path('search/', views.search, name='search'),
    # 加入购物车指定本书（缺省为1）
    path('buy/', views.buy, name='buy'),
    # 删除用户购物车中商品的信息
    path('cancel/', views.cancel, name='cancel'),
    # 购物车书数目设置为
    path('set_number/', views.set_number, name='set_number'),
    # 购物车书选中状态反转
    path('select/', views.select, name='select'),
    # 获取用户购物车中商品的数量（无论选不选中的商品种类数）
    path('count/', views.count, name='count'),
    # 购物车已选中数量
    path('select_count/', views.select_count, name='select_count'),
    #path('update/', views.cart_update, name="update"),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('user/', include('user.urls')),
    path('book/', include('book.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

order/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'order'
urlpatterns = [
    # 自己的全部订单
    path('all/', views.all, name='all'),
    # 订单详情
    path('detail/<int:order_id>/', views.detail, name='detail'),
    # 将购物车中的全部货物提交订单
    path('new/', views.new, name='new'),
    # 立即购买 直接创建订单
    path('buynow/', views.buynow, name='buynow'),
    # 订单确认收货
    path('receive/', views.receive, name='receive'),
    # 订单支付宝支付
    path('alipay_pay/', views.alipay_pay, name='alipay_pay'),
    # （已改为一般函数）
    # path('alipay_query/', views.alipay_query, name='alipay_query'),
]

user/urls.py
from django.urls import path

from . import views

# 多个app
app_name = 'user'
urlpatterns = [
    # ex: /user/
    path('login/', views.login, name='login'),
    path('detail/', views.detail, name='detail'),
    path('register/', views.register, name="register"),
    path('result/', views.result, name="result"),
    path('logout/', views.logout, name="logout"),
    path('cart/', views.cart, name="cart"),
    # path('order/', views.order, name="order"), TODO 订单确认页面
    path('verifycode/', views.verifycode, name="verifycode"),
    path('verifyemail/', views.verifyemail, name="verifyemail"),
    path('login_check/', views.login_check, name="login_check"),
    # path('register_update/', views.register_update, name="register_update"), TODO 更新个人信息

    #关于统计信息的超级用户的url
    path('super/', views.super_host, name="super_host"),
    path('super/book/<int:pageid>/', views.super_book, name="super_book"),
    path('super/book/bookadd/', views.super_bookadd, name="super_bookadd"),
    path('super/book/create/', views.super_bookCreate, name="super_bookCreate"),
    path('super/book/delete/<int:bookid>/', views.super_bookDelete, name="super_bookDelete"),
    path('super/book/change/<int:bookid>/', views.super_bookChange, name="super_bookChange"),
    path('super/book/update/<int:bookid>/', views.super_bookUpdate, name="super_bookUpdate"),
    path('super/statistic/', views.statistic, name="statistic"),
    path('super/order/<int:pageid>/', views.super_order, name="super_oder"),
    path('super/order/status/<int:orderid>/', views.super_orderSta),
]

order/models.py
from django.db import models

# Create your models here.


class Order(models.Model):
    def __str__(self):
        return str(self.order_id)

    order_id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    sum_price = models.FloatField()
    # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
    status = models.IntegerField()
    time_submit = models.DateTimeField()
    time_pay = models.DateTimeField(null=True)
    time_finish = models.DateTimeField(null=True)


class OrderContent(models.Model):
    def __str__(self):
        return str(self.book_id)

    order_id = models.IntegerField()
    book_id = models.IntegerField()
    number = models.IntegerField()
    price = models.FloatField()

user/models.py
from django.db import models

import datetime
from django.utils import timezone


# Create your models here.


class User(models.Model):
    def __str__(self):
        return self.user_name

    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=16)
    phone_number = models.CharField(max_length=20)  # +86 0311 86012345
    address = models.CharField(max_length=100)
    email = models.CharField(max_length=50, unique=True)
    register_date = models.DateField()


class Cart(models.Model):
    def __str__(self):
        return str(self.user_id) + '的购物车'

    user_id = models.IntegerField(primary_key=False)
    book_id = models.IntegerField()
    number = models.IntegerField(default=1)
    price = models.FloatField()
    select = models.BooleanField(default=True)

order/views.py
import io

from django.forms import model_to_dict
from django.http import JsonResponse, Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
from book.models import Book
from user.models import Cart
from order.models import Order, OrderContent
from django.core import serializers
from bookstore import settings

import datetime

from alipay import AliPay  # https://blog.csdn.net/appleyuchi/article/details/104613313
import qrcode, time
import urllib

from bookstore.views import login_needful, login_needful_json_res_0_errmsg


@login_needful
def all(request) -> HttpResponse:
    """用户的所有信息"""
    user_id = request.session['user']['user_id']

    # 更新待支付订单状态
    for order in Order.objects.filter(user_id=user_id, status=1):
        # ？频繁连续查询失败概率明显提高？同一顾客不太可能有过多待支付订单
        order_status_update(order)
    def Add_Content(order):
        dic = {0: '已取消', 1: '待付款', 2: '待发货', 3: '已发货', 4: '已完成'}
        order = model_to_dict(order)
        order['status'] = dic[order['status']]
        order_content_list = OrderContent.objects.filter(order_id=order['order_id'])
        order_content = []
        for o_c in order_content_list:
            o_c = model_to_dict(o_c)
            o_c['books'] = Book.objects.get(book_id=o_c['book_id'])
            o_c['price'] = o_c['price'] * o_c['number']
            order_content.append(o_c)
        order['order_content'] = order_content
        return order
    cancel_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=0)]
    unpaid_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=1)]
    unsent_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=2)]
    unreceived_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=3)]
    finished_list = [Add_Content(order) for order in Order.objects.filter(user_id=user_id, status=4)]
    content = {
        'cancel_list': cancel_list,
        'unpaid_list': unpaid_list,
        'unsent_list': unsent_list,
        'unreceived_list': unreceived_list,
        'finished_list': finished_list,
    }
    # 因为没有对应前端，先返回成json
    return render(request, 'order/all.html', content)


@login_needful
def detail(request, order_id: int):
    """订单详情 TODO 只能查看自己的订单"""
    content = {}
    # 订单本身的信息
    try:
        order = Order.objects.get(order_id=order_id)
    except Cart.DoesNotExist:
        return Http404
    except Cart.MultipleObjectsReturned:
        raise Exception('同一订单号出现多次')

    # 更新待支付订单状态
    order_status_update(order)

    # object 转 dict
    content['order'] = model_to_dict(order)
    # 计算总付款数=总价+运费
    content['order']['all_price'] = content['order']['sum_price'] + 10
    content['order']['status_str'] = settings.STATUS_NUM_TO_STR[order.status]

    # 订单中书籍的信息
    content['order_content'] = []
    order_content = OrderContent.objects.filter(order_id=order_id)
    content['count'] = len(order_content)
    for book in order_content:
        element = {
            'id': book.order_id,
            'book_id': book.book_id,
            'number': book.number,
            'price': book.price * book.number,  # 小计：可能不只一本同种书的总价
        }
        try:
            book = Book.objects.get(book_id=book.book_id)
        except Cart.DoesNotExist:
            raise Exception('书编号%d不存在' % book.book_id)
        except Cart.MultipleObjectsReturned:
            raise Exception('书编号%d出现多次' % book.book_id)
        element.update({
            'book_name': book.book_name,
            'book_picture': book.book_picture,
            'book_price': book.price,
            'author': book.author,
            'press': book.press,
            'kind_name': book.kind_name,
        })
        content['order_content'].append(element)
        #收货地址
        content['address'] = request.session['user']['address']
        content['user_name'] = request.session['user']['user_name']
        content['phone_number'] = request.session['user']['phone_number']
    return render(request, 'order/detail.html', content)


@login_needful
def new(request):
    """创建订单，以购物车中选中的商品"""
    order = Order(
        # order_id =
        user_id=request.session['user']['user_id'],
        sum_price=0,
        # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
        status=1,
        time_submit=datetime.datetime.now(),
        # time_pay=None,
        # time_finish=None,
    )
    order.save()

    sum_price = 0.0
    for book in Cart.objects.filter(
            user_id=request.session['user']['user_id'],
            select=True,
    ).all():
        OrderContent.objects.create(
            order_id=order.order_id,
            book_id=book.book_id,
            number=book.number,
            price=book.price
        )
        sum_price += book.number * book.price
    Order.objects.filter(order_id=order.order_id).update(sum_price=sum_price)
    Cart.objects.filter(
        user_id=request.session['user']['user_id'],
        select=True,
    ).delete()
    # 重定向展示实际的网址
    return redirect("/order/detail/%d" % order.order_id)


@login_needful_json_res_0_errmsg
def buynow(request) -> JsonResponse:
    """立即购买，以给定数量当前商品创建订单"""
    try:
        book_id = int(request.GET.get('book_id'))
        number = int(request.GET.get('number', 1))
    except ValueError:
        # 商品数目不合法
        return JsonResponse({'res': 0, 'errmsg': '商品数量必须为数字'})
    book = Book.objects.get(book_id=book_id)

    order = Order(
        user_id=request.session['user']['user_id'],
        sum_price=number*book.price,
        # 订单状态：已取消 0， 待付款 1， 待发货 2， 已发货 3， 已完成 4
        status=1,
        time_submit=datetime.datetime.now()
    )
    order.save()

    OrderContent.objects.create(
        order_id=order.order_id,
        book_id=book_id,
        number=number,
        price=book.price
    )
    return JsonResponse({'res':1, 'order_id':order.order_id})


@login_needful_json_res_0_errmsg
def receive(request) -> JsonResponse:
    """订单收货 TODO 仅限自己的订单"""
    try:
        order_id = int(request.GET.get('order_id'))
    except ValueError:
        return JsonResponse({'res': 0, 'errmsg': '订单号错误'})
    try:
        order = Order.objects.get(user_id=request.session['user']['user_id'], order_id=order_id)
    except Order.DoesNotExist:
        # 订单不存在
        return JsonResponse({'res': 0, 'errmsg': '订单不存在'})
    except Order.MultipleObjectsReturned:
        raise Exception('订单表错误')
    if order.status == 3:
        # 将可收货的订单收货
        order.status = 4
        order.save()
        return JsonResponse({'res': 1})
    else:
        return JsonResponse({'res': 0, 'errmsg': '订单不可收货'})


alipayClient = AliPay(
    appid=settings.APP_ID,
    app_notify_url=None,
    app_private_key_string=settings.APP_PRIVATE_KEY,
    alipay_public_key_string=settings.ALIPAY_PUBLIC_KEY,
    sign_type='RSA2',
    debug=settings.DEBUG,
)


def build_trade_no(order_id: int, date_time: datetime):
    """以订单号和日期时间构造支付宝订单号"""
    return (str(order_id) + '__%s' % date_time).split('.')[0].replace(' ', '_').replace('-', '_').replace(':', '_')


def alipay_pay(request):
    """获取支付宝支付二维码 TODO 限用户个人"""
    global alipayClient

    order_id = request.GET.get('order_id')
    if order_id is None:
        print('无order_id')
        return
    try:
        order_id = int(order_id)
    except ValueError:
        print('order_id非整数')
        return
    try:
        order = Order.objects.get(order_id=order_id)
    except Order.DoesNotExist:
        # 订单不存在
        print('order_id 订单不存在')
        return
    except Order.MultipleObjectsReturned:
        raise Exception('订单表错误')

    # 支付宝订单号
    out_trade_no = build_trade_no(order_id, order.time_submit)
    print(out_trade_no)
    # 书籍总价加运费
    total_amount = order.sum_price + 10.00
    subject = '珞珈在线书店订单 %s' % order.time_submit
    timeout_express = '30m'
    try:
        dict = alipayClient.api_alipay_trade_precreate(out_trade_no=out_trade_no, total_amount=total_amount,
                                                       subject=subject, timeout_express=timeout_express)
    except urllib.error.URLError:
        raise Exception('网络已断开')

    # https://www.cnblogs.com/linjiqin/p/4140455.html
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=2,  # 图片尽可能小，但足以识别（结果一般为86*86像素）
        border=1
    )
    qr.add_data(dict['qr_code'])  # 从URL获取二维码所含信息
    img = qr.make_image()  # 生成二维码图片
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为png
    img.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


def alipay_query(out_trade_no: str):
    """查询支付宝未付款订单最新状态"""
    global alipayClient
    try:
        result = alipayClient.api_alipay_trade_query(out_trade_no=out_trade_no)
    except:
        return {'res': 0}

    try:
        order_id = int(out_trade_no.split('_')[0])
    except ValueError:
        raise Exception('order_id非整数 %s' % out_trade_no)

    if result.get('code', '') == '40004':
        if result.get('sub_code', '') == 'ACQ.TRADE_NOT_EXIST':
            # 用户未扫码，支付宝订单未创建
            return {'res': 1, 'status': 1}
        else:
            # 调用失败
            return {'res': 0}
    elif result.get('code', '') == '10000':
        try:
            order = Order.objects.get(order_id=order_id)
        except Order.DoesNotExist:
            # 订单不存在
            raise Exception('order_id 订单不存在 %d' % order_id)
        except Order.MultipleObjectsReturned:
            raise Exception('订单表错误 %d' % order_id)

        # 待支付状态的订单才会被查询，若未支付无需更新
        if result.get("trade_status", "") == "WAIT_BUYER_PAY":
            # 用户扫码，未支付
            return {'res': 1, 'status': 1}
        elif result.get("trade_status", "") == "TRADE_SUCCESS":
            # 用户已支付
            order.status = 2
            order.time_pay = datetime.datetime.now()
            order.save()
            return {'res': 1, 'status': 2}

templates/user/cart.html
{% extends 'base.html' %}
{% load static %}
{% block topfiles %}
<script>

    $(function() {
    // update_cart_count() //书籍总数：页面加载时直接给出
    update_total_price_checked() //书籍总价
    function update_cart_count() {
        //  更新列表上方商品总种类数
        $.get('/book/count/', function (data) {
            $('.total_kinds_count').children('em').text(data.res)
        })
    }

    // 计算所有被选中商品的总价，总数目和商品的小计
    function update_total_price_checked() {
        update_select_count() // 改变上栏已选中书籍数量
        total_count = 0
        total_price = 0
        total_checked = true
        // 获取所有无论是否选中的商品所在的ul元素
        $('.cart_list_td').each(function () {
            // 计算商品的小计
            res_dict = update_book_price($(this))
            if(res_dict.book_checked) {// 只计算选中商品的价格、数量
                total_count += res_dict.book_count
                total_price += res_dict.book_amount
            }
            total_checked = total_checked && res_dict.book_checked
        })
        // 设置商品的总价和总数目
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)
        // 更新选择框状态
        $('.settlements').find(":checkbox").prop('checked', total_checked)
    }

    function update_book_price(book_ul) {
        book_checked = book_ul.find('input').prop("checked")
        // 获取每一个商品的价格和数量
        book_price = book_ul.children('.col05').text()
        book_count = book_ul.find('.num_show').val()

        // 计算商品的小计
        book_price = parseFloat(book_price)
        book_count = parseInt(book_count)
        book_amount = book_price * book_count

        return {
            'book_count': book_count,
            'book_amount': book_amount,
            'book_checked': book_checked
        }
    }

    $('.del_btn').click(function () {
        // 获取删除的商品的id
        book_ul = $(this).parents('ul')
        book_id = book_ul.find('.num_show').attr('book_id')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params = {
            "book_id": book_id,
            "csrfmiddlewaretoken": csrf
        }
        $.get('/book/cancel/', params, function (data) {
            if (data.res === 1){
                // 删除成功
                // 移除商品对应的ul元素
                book_ul.remove()
                // 更新总价和总选中
                update_total_price_checked()
                // 更新页面购物车商品总数
                update_cart_count()
            }
        })
    })

    $('.add').click(function () {
        // 获取增加的商品的id
        book_ul = $(this).parents('ul')
        book_id = book_ul.find('.num_show').attr('book_id')
        book_num = Number(book_ul.find('.num_show').attr('value'))+1
        if(!Number.isInteger(book_num)) {
            return
        }
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params = {
            "book_id": book_id,
            'number': book_num,
            "csrfmiddlewaretoken": csrf
        }
        $.get('/book/set_number/', params, function (data) {
            if (data.res === 1){
                // 加一成功
                // 修改当前数量
                book_ul.find('.num_show').attr('value', book_num)
                // 判断商品对应的checkbox是否选中
                is_checked = book_ul.find(':checkbox').prop('checked')
                if (is_checked){
                    update_total_price_checked()
                }
            }
        })
    })


    $('.minus').click(function () {
        // 获取增加的商品的id
        book_ul = $(this).parents('ul')
        book_id = book_ul.find('.num_show').attr('book_id')
        book_num = Number(book_ul.find('.num_show').attr('value'))-1
        if(!Number.isInteger(book_num)) {
            return
        }
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params = {
            "book_id": book_id,
            'number': book_num,
            "csrfmiddlewaretoken": csrf
        }
        $.get('/book/set_number/', params, function (data) {
            if (data.res === 1){
                // 减一成功
                if(book_num===0) {
                    // 减为0
                    // 移除商品对应的ul元素
                    book_ul.remove()
                    // 更新页面购物车商品总数
                    update_cart_count()
                }else{
                    // 修改当前数量
                    book_ul.find('.num_show').attr('value', book_num)
                }
                update_total_price_checked()
            }
        })
    })

    // 点击复选框效果
    $('.cart_list_td .col01 input').click(function () {
        // 反转选中状态
        book_ul = $(this).parents('ul')
        book_id = book_ul.find('.num_show').attr('book_id')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params = {
            "book_id": book_id,
            "csrfmiddlewaretoken": csrf
        }
        $.get('/book/select/', params, function (data) {
            if (data.res === 1){
                // 反转成功
                // 更新总价选择框状态
                update_total_price_checked()
            }
        })
    })

    // 点击全选复选框效果
    $('.settlements .col01 input').click(function () {
        // 点击全选
        total_checked = $(this).prop('checked')
        $('.cart_list_td').each(function () {
            // 计算商品的小计
            checked = $(this).find('.col01 input').prop("checked")
            if(checked !== total_checked){
                // 与当前（点击后）全选状态不同的都模拟点击一次
                $(this).find('.col01 input').click()
            }
        })
        $(this).prop('checked', !total_checked)

        update_total_price_checked()
    })
    })



</script>
{% endblock topfiles %}
{% block body %}
    <div class="total_kinds_count">全部商品<em>{{ total_kinds_count }}</em>种</div>
    <ul class="cart_list_th clearfix">
        <li class="col01">封面名称</li>
        <li class="col02">作者</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">出版社</li>
        <li class="col06">操作</li>
    </ul>

    {% for cart in cart_list %}
    <ul class="cart_list_td clearfix">
        {# 提交表单时，如果checkbox没有被选中，它的值不会被提交 #}
        <li class="col01"><input type="checkbox" name="book_id" value="{{ cart.book_id }}" {% if cart.select %} checked {% endif %}></li>
        <li class="col02"><a href="../../book/detail/{{ cart.book_id }}"><img src="{% static cart.book.book_picture %}" alt=""></a></li>
        <li class="col03">{{ cart.book.book_name }}<br><em>{{ cart.book.price }}元</em></li>
        <li class="col04">{{ cart.book.author }}</li>
        <li class="col05">{{ cart.price }}</li>
        <li class="col06">
            <div class="num_add">
                <a href="javascript:" class="add fl">+</a>
                <input type="text" book_id="{{ cart.book_id }}" class="num_show fl" value="{{ cart.number }}">
                <a href="javascript:" class="minus fl">-</a>
            </div>
        </li>
        <li class="col07">{{ cart.book.press }}</li>
        <li class="col08"><a href="javascript:" class="del_btn" id="{{ cart.book_id }}">删除</a></li>
    </ul>
    {% endfor %}

    <ul class="settlements">
        <li class="col01"><input type="checkbox" name="" checked=""></li>
        <li class="col02">全选</li>
        <li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>[加载中]</b>件商品</li>
        <li class="col04"><a href="{% url 'order:new' %}" class="add_cart" id="submit_order">提交订单</a></li>
        {% csrf_token %}
    </ul>

{% endblock %}

templates/user/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:detail' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'order:all' %}">· 全部订单</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
                <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                        <ul class="user_info_list1">
                            <li><span>用户名：</span>{{ user_name }}</li>
                            <li><span>联系方式：</span>{{ phone_number }}</li>
                            <li><span>电子邮箱:</span>{{ email }}</li>
                            <li><span>注册日期：</span>{{ register_date }}</li>
                        </ul>
                </div>
        </div>
    </div>
{% endblock body %}

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 获取用户名和密码
            var user_name = $('#user_name').val()
            var password = $('#pwd').val()
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            var remember = $('input[name="remember"]').prop('checked')
            var verifycode = $('input[name="vc"]').val()
            // 发起ajax请求
            var params = {
                'user_name': user_name,
                'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode': verifycode,
            }
            $.post('/user/login_check/', params, function (data) {
                // 用户名密码错误 {'res':0}
                // 登录成功 {'res':1}
                console.debug(data.res);
                console.debug(data.errmsg);
                if (data.res == 0){
                    $('#user_name').next().html(data.errmsg).show()
                    $('#verifycode').click()
                }
                else
                {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}

{% block search_bar %}{% endblock search_bar %}

{% block body %}
    <div class="login_top clearfix">
        <a href="{% url 'index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
<!--            <div class="slogan fl">学计算机 · 来尚硅谷</div>-->
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    {% csrf_token %}
                    <input type="text" id="user_name" class="name_input" value="{{ user_name }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
<!--                    <div class="pwd_error">输入错误</div>-->
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <div style="top: 100px; position: absolute;">
                        <input type="text" id="vc" name="vc">
                        <img id='verifycode' src="/user/verifycode/" onclick="this.src='/user/verifycode/?'+Math.random()" alt="CheckCode"/>
                    </div>
                    <input type="button" id="btnLogin" value="登录" class="input_submit">
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{% block cart_count %}
{% endblock cart_count %}

templates/user/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
    
{% endblock body %}

templates/user/result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}珞珈线上书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}
    <p><strong>{{ error_message }}</strong></p>
{% endblock body %}